#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2014, Laurent Grawet <dev@grawet.be>                             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to monitor the free and used space of a datastore
###############################################################################

# ------------ Set up the environment to source common tools ------------

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh
source ${DRIVER_PATH}/v7000.conf
source ${DRIVER_PATH}/scripts_v7000.sh

# -------- Get datastore arguments from OpenNebula core ------------

DRV_ACTION=$1
ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"

unset i XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/MGMT \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/MDISK_GROUP)

MGMT="${XPATH_ELEMENTS[0]:-$MGMT}"
MDISK_GROUP="${XPATH_ELEMENTS[1]:-$MDISK_GROUP}"

# ------------ Compute datastore usage -------------

MONITOR_CMD="set -e ; svcinfo lsmdiskgrp -nohdr -bytes -delim : -filtervalue name=${MDISK_GROUP}"

MONITOR_DATA=$(v7000_ssh_monitor_and_log $MGMT "$MONITOR_CMD")
MONITOR_STATUS=$?

if [ "$MONITOR_STATUS" = "0" ]; then
    echo USED_MB=`echo $MONITOR_DATA | awk -F\: '{print $10/1024^2}'`
    echo TOTAL_MB=`echo $MONITOR_DATA | awk -F\: '{print $6/1024^2}'`
    echo FREE_MB=`echo $MONITOR_DATA | awk -F\: '{print $8/1024^2}'`
else
    echo "$MONITOR_DATA"
    exit $MONITOR_STATUS
fi
